name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
             echo "Pulling latest changes from GitHub..."
              cd /opt/odoo/titik-koma-odoo
              git pull origin main
  
              echo "Stopping Odoo container to release port..."
              cd deployment
              docker compose stop web
  
              echo "Upgrading modules to apply XML/UI changes..."
              docker compose run --rm web odoo \
                -u titikkoma,student_journaling,assessment,konseling,mental_health,student_mood_tracking,custom_login,edit_profil2 \
                -d titik_koma_db \
                --stop-after-init
  
              echo "Starting Odoo container with new code..."
              docker compose start web
  
              echo "Deployment successful!"
